#!/usr/bin/env bash
set -euo pipefail

PROJECT_ID="${PROJECT_ID:-allpath}"
REGION="${REGION:-us-central1}"
SERVICE_NAME="${SERVICE_NAME:-allpath-web}"
IMAGE_TAG="${IMAGE_TAG:-$(git rev-parse --short HEAD 2>/dev/null || date +%Y%m%d%H%M%S)}"
FIRESTORE_DATABASE_ID="${FIRESTORE_DATABASE_ID:-default}"
OPENROUTER_SITE_URL="${OPENROUTER_SITE_URL:-https://all-path.com}"
OPENROUTER_APP_NAME="${OPENROUTER_APP_NAME:-AllPath}"
OPENROUTER_API_KEY_SECRET="${OPENROUTER_API_KEY_SECRET:-OPENROUTER_API_KEY}"
TRIAL_COOKIE_SECRET_NAME="${TRIAL_COOKIE_SECRET_NAME:-TRIAL_COOKIE_SECRET}"
TRIAL_ENCRYPTION_SECRET_NAME="${TRIAL_ENCRYPTION_SECRET_NAME:-TRIAL_ENCRYPTION_SECRET}"
# Firebase Auth web config (optional; empty = auth disabled in the build).
NEXT_PUBLIC_FIREBASE_API_KEY="${NEXT_PUBLIC_FIREBASE_API_KEY:-}"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:-}"
NEXT_PUBLIC_FIREBASE_PROJECT_ID="${NEXT_PUBLIC_FIREBASE_PROJECT_ID:-}"
NEXT_PUBLIC_FIREBASE_APP_ID="${NEXT_PUBLIC_FIREBASE_APP_ID:-}"

GCLOUD_BIN="${GCLOUD_BIN:-/opt/homebrew/share/google-cloud-sdk/bin/gcloud}"
CLOUDSDK_CONFIG="${CLOUDSDK_CONFIG:-$PWD/.gcloud}"
CLOUDSDK_PYTHON="${CLOUDSDK_PYTHON:-/opt/homebrew/bin/python3}"
mkdir -p "$CLOUDSDK_CONFIG"
export CLOUDSDK_CONFIG
if [ -x "$CLOUDSDK_PYTHON" ]; then
  export CLOUDSDK_PYTHON
fi

echo "Using gcloud: $GCLOUD_BIN"
echo "Project: $PROJECT_ID | Region: $REGION | Service: $SERVICE_NAME | Tag: $IMAGE_TAG"
echo "Firestore DB: $FIRESTORE_DATABASE_ID | Site URL: $OPENROUTER_SITE_URL | App Name: $OPENROUTER_APP_NAME"
echo "Secrets: $OPENROUTER_API_KEY_SECRET, $TRIAL_COOKIE_SECRET_NAME, $TRIAL_ENCRYPTION_SECRET_NAME"

"$GCLOUD_BIN" config set project "$PROJECT_ID" >/dev/null

"$GCLOUD_BIN" builds submit \
  --config cloudbuild.yaml \
  --substitutions "_SERVICE_NAME=${SERVICE_NAME},_REGION=${REGION},_IMAGE_TAG=${IMAGE_TAG},_FIRESTORE_DATABASE_ID=${FIRESTORE_DATABASE_ID},_OPENROUTER_SITE_URL=${OPENROUTER_SITE_URL},_OPENROUTER_APP_NAME=${OPENROUTER_APP_NAME},_OPENROUTER_API_KEY_SECRET=${OPENROUTER_API_KEY_SECRET},_TRIAL_COOKIE_SECRET_NAME=${TRIAL_COOKIE_SECRET_NAME},_TRIAL_ENCRYPTION_SECRET_NAME=${TRIAL_ENCRYPTION_SECRET_NAME},_NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY},_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN},_NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID},_NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}" \
  .

echo
echo "Deploy done. Get URL with:"
echo "$GCLOUD_BIN run services describe $SERVICE_NAME --region $REGION --format='value(status.url)'"
